project_id = "mbkvzgohhfodxfubejgd"

[functions.extract-gallery]
verify_jwt = false

[functions.download-gallery]
verify_jwt = false

[functions.progress]
verify_jwt = false

[functions.search-content]
verify_jwt = false