project_id = "mbkvzgohhfodxfubejgd"

[global.env]
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_ANON_KEY = "env(SUPABASE_ANON_KEY)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"

[[functions]]
name = "search-content"
verify_jwt = false