// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mbkvzgohhfodxfubejgd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ia3Z6Z29oaGZvZHhmdWJlamdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTk2NDYzODMsImV4cCI6MjAzNTIyMjM4M30.Wa5BXiz56VYG3pcr9ESCj7i0KByInawgYxY3fMsi8zA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);